### ISSUE TITLE
Mention alternatives to NPM/Node/Bower

### ISSUE THREAD

**Issue by paf31** [purescript/purescript.github.io#124]
It might be worth mentioning that alternatives exist, alongside the default recommendation to use NPM/Bower.

**Comment by hdgarrood** [comment]
I agree to an extent but I think we need to be careful not to overwhelm people with choices they're not yet equipped to make, so I'm not sure.

**Comment by thecotne** [comment]
just to mention here bower is deprecated https://github.com/bower/bower/issues/2298

**Comment by hdgarrood** [comment]
The default recommendation is npm and spago now, via #138, so that solves the issue of bower being not great. As for npm, the only alternative I'm aware of is yarn, and yarn 2 doesn't work with native binaries in js packages, which both the `purescript` and `spago` npm packages use. So I don't think yarn is a good recommendation either. Not using npm at all is also an option, but in that case people can probably manage to download the binaries on their own. I think I'm going to close this because a) presenting people with too many choices at this stage is a bad UX, b) it's not clear what the alternatives would really be at this point, and c) the issue hasn't seen activity in quite a while.
