### ISSUE TITLE
Add more talks

### ISSUE THREAD

**Issue by paf31** [purescript/purescript.github.io#30]
We could add [this](https://www.youtube.com/watch?v=OdenKPwSPss) nice talk from LambdaJam/YOW 2015 to the Learn page, if @michaelficarra doesn't mind.

**Comment by paf31** [comment]
Here is [another](https://www.youtube.com/watch?v=4bAYr90dkls) by @tfausak.

**Comment by tfausak** [comment]
Thanks! I should have the slides up on [my personal site](http://taylor.fausak.me) shortly.

**Comment by garyb** [comment]
:+1:

**Comment by michaelficarra** [comment]
Thanks for pointing this out, @paf31. I didn't even know the video had been published. The slides are hard to see (it was very bright in the room), so follow along with them at https://speakerdeck.com/michaelficarra/getting-started-with-purescript.

**Comment by tfausak** [comment]
No love for my talk?

**Comment by garyb** [comment]
Just an oversight I imagine :)

**Comment by paf31** [comment]
I'd like to add it but I wasn't sure how to list it since the others have a conference title. Is there an event title I can use?

**Comment by tfausak** [comment]
We call the events "Lunch & Learn"s. That's what I put in my PR (#41).

**Comment by garyb** [comment]
@tfausak I liked your talk by the way. The `bower`/`npm` thing: `npm` doesn't support flat dependencies in the manner that we need, and hierarchical dependencies wouldn't work for PureScript code. I've been convinced by the argument we should rely less on transitive dependencies, but we have no way of enforcing it without making another tool, and even then it would be optional to run...

**Comment by garyb** [comment]
Also the granular imports thing: until fairly recently we didn't have re-exports working reliably and as fully as we'd like, so there's plenty of room to improve the situation there, we just haven't applied the re-exporting everywhere that would benefit from it yet.

**Comment by tfausak** [comment]
Thanks @garyb! I figured there were some good reasons for the nits I picked, but I didn't have enough time to fully research them. 

I don't like transitive dependencies because I don't want my app to break because I accidentally relied on package Y when I only cared about package X. Although I do like the utility of meta packages like purescript-base and (my own) purescript-batteries. They let you bring in a whole set of packages with a single dependency. 

And the granular imports are pretty easy to work around by creating your own `Prelude` module or whatever. The granularity is actually nice when building your own core module because you can easily get exactly what you need.

Anyway, thanks for the feedback!
