### ISSUE TITLE
Use flexbox

### ISSUE THREAD

**Issue by paf31** [purescript/purescript.github.io#55]
Seems most modern browsers support it now, and it will probably tidy up some of the compass-generated CSS. Thoughts?

**Comment by AppShipIt** [comment]
I tend to prefer CSS frameworks over rolling my own grid layouts.

**Comment by garyb** [comment]
I don't really see the point in changing from what we have. We do minimal work maintaining the CSS, and the layout parts of it are actually quite simple - I don't think flexbox gives us anything we need, since most of the content is made up of variations on a list.

If we want to avoid compass we can probably do that though, and just switch to libsass. I don't think we're using any compass features now, except perhaps prefixing for CSS3 columns, which we can reproduce manually easily enough as it's only used in one place.

**Comment by paf31** [comment]
Makes sense.
