### ISSUE TITLE
Make examples on front page runnable

### ISSUE THREAD

**Issue by paf31** [purescript/purescript.github.io#59]
Or at least link to Try PureScript with the appropriate gists.

**Comment by garyb** [comment]
I wonder if we could do something flare-y with these? I found the generic-highlighted flarecheck stuff pretty inspiring. /cc @sharkdp

I'm not exactly sure how that would fit with what we have though :smile:

**Comment by paf31** [comment]
Absolutely, I think that would be great.

**Comment by paf31** [comment]
Or we could use a `contentEditable` div with the Try PureScript API.

**Comment by sharkdp** [comment]
> Or at least link to Try PureScript with the appropriate gists.

I think a "Edit and run" link for each of the examples would be a reasonable solution. Otherwise, you would probably end up copying most of the try-purescript machinery (Ace editor, iframe, ..) in order not to lose any of the functionality (?).

> I wonder if we could do something flare-y with these? I found the generic-highlighted flarecheck stuff pretty inspiring. /cc @sharkdp
> 
> I'm not exactly sure how that would fit with what we have though

As much as I would like to see Flare being used, I'm also not sure how it would fit in. After all, the front-page examples should probably serve to demonstrate PureScripts language features. If you have any ideas tough, I'd be very happy to help! :smile:
