### ISSUE TITLE
Hook up Hakyll again

### ISSUE THREAD

**Issue by garyb** [purescript/purescript.github.io#8]

**Comment by hdgarrood** [comment]
:+1: as, presumably, this would make it clearer how to rebuild the HTML - my pull request removing `pulp dep`, #53, was merged, but the HTML still has the old text which uses the (deprecated) `pulp dep`, and also doesn't tell you to `npm install -g bower` (which is now necessary). I'd happily update it myself but I don't know how.

**Comment by garyb** [comment]
I was going to say "it's just HTML", but I guess not for the articles. I don't know how they're updated either! Although the readme does say `TODO: Describe how the Pandoc Markdown => HTML process works.`.

**Comment by hdgarrood** [comment]
I think we might need a template or something, as I did try regenerating it using pandoc, and it mostly worked, but I couldn't work out how to preserve the stuff around the edges, like the `<head>`, the menu bar at the top, and the google analytics stuff at the bottom.

**Comment by paf31** [comment]
I use the "copy and paste it into the HTML" approach. :disappointed:

**Comment by AppShipIt** [comment]
I'd like to propose (and personally implement) a transition to Brunch (cf. purescript/roadmap#46) for the static build for the following reasons:

1. Simplified workflow with more web development tools (e.g. Jade templates).
2. More familiar to non-Haskell aesthetes and front end developers in general.
4. PureScript should be used for tooling and purescript-brunch would further that cause.

**Comment by hdgarrood** [comment]
I'm actually halfway through setting up Hakyll right now. I've just looked briefly at the Brunch website but it seems like it's aimed at client-side applications rather than static websites. Of course there's significant overlap between these two categories, but Hakyll's home page does sound like it's designed with exactly what we want in mind, whereas Brunch's doesn't.

**Comment by AppShipIt** [comment]
> Hakyll's home page does sound like it's designed with exactly what we want in mind, whereas Brunch's doesn't.

Could you expound? I've used Brunch and a couple other static site generators and Hakyll doesn't qualify for the list of reasons I provided.

**Comment by hdgarrood** [comment]
Realistically, it's mostly going to be the same people who are working on the compiler who are going to do anything to the website, so "protecting" people from Haskell isn't an issue.

Hakyll says it's for "generating static web sites". The first thing on the Brunch homepage is a ton of complex stuff that you might worry about if you were making a big frontend application, but not what we need for the purescript website (which is almost entirely just HTML).

**Comment by AppShipIt** [comment]
> it's mostly going to be the same people who are working on the compiler who are going to do anything to the website

I strongly disagree and ask the team to reconsider. The burden of maintenance for the site design shouldn't (from a design standpoint let alone time) ultimately rest on the compiler maintainers. It's why we currently have unimplemented low hanging fruit.

> Brunch homepage is a ton of complex stuff that you might worry about if you were making a big frontend application

That's basically the feedback I get the first time a JavaScript developer looks at PureScript and equally invalid.

> not what we need for the purescript website (which is almost entirely just HTML).

…as it stands today. It doesn't have to be Brunch but it should be JavaScript. Why are we developing Node tooling at all if we don't use it?

**Comment by hdgarrood** [comment]
It absolutely should not be JavaScript. I've seen lots of static sites which are all just JS when they should have been HTML, and they're almost invariably crap. Things like broken back buttons, broken bookmarking / URLs, flashes of templates before the actual content comes up, caching doesn't work nearly as well as it does with just HTML, NoScript is a thing... Yes, I know you can avoid some of these issues if you use the relevant APIs extremely carefully, but *you get all this for free when you use HTML*.

I've already invested a not-insignificant of time into setting up Hakyll and so the last thing I want to do is to drop that and go to learn *yet another* JS build tool. I know that Hakyll works for what we want here (because I've used it before), and I also know that I will be able to go in and read the source and understand it if I need to (as will @paf31 and @garyb and most other compiler contributors). This is most definitely not the case for most stuff written in JS. Also, it's approximately 5000x times easier to get your head around the API when the docs tell you "this is a Monad, this is a Monoid" etc, as opposed to the normal level of JS documentation, which usually only gets you as far as being able to cope with situations the documentation authors explicitly considered while they were writing it.

**Comment by AppShipIt** [comment]
Driving but clarification * JavaScript build tool (not JS). On some level I don't care how much we've invested in Hakyll if it keeps web developers from PRing. For contributors who know Haskell I'd rather see them solving more difficult problems.

**Comment by hdgarrood** [comment]
Once Hakyll is up and running, 99% of changes won't require any Haskell knowledge at all - just Markdown. It's very rare you have to edit the `site.hs` file.

**Comment by AppShipIt** [comment]
Fundamentally I think we shouldn't be using Haskell outside the compiler when more capable tools exist on the platform we're targeting.

**Comment by hdgarrood** [comment]
How about this: I'll finish up what I'm doing with Hakyll (I'm nearly done), and then we can examine your claim that more capable tools exist and consider alternatives. Right now I really just want to get the website updated so that people aren't getting confused.

**Comment by AppShipIt** [comment]
Fair enough. I'm also thinking long term. I should start a port to substantiate my claim anyway. Likewise it's possible my perspective of Hakyll is skewed by unfamiliarity.

**Comment by garyb** [comment]
I have no particular preference for whatever tool we use, as long as it's easy. :smile: I don't particularly love Hakyll, I've only used it once before, and that's when we had the "blog version" of the site.

I'd never heard of Brunch until it was mentioned in the other thread recently either, fwiw, so it's not necessarily more familiar to front end developers.

**Comment by hdgarrood** [comment]
Resolved by #66?

**Comment by paf31** [comment]
Yes, thanks!
